import { NgModule } from '@angular/core';
import { MatDialogModule } from '@angular/material/dialog';

import {
  MatCardModule,
  MatIconModule,
  MatButtonModule,
  MatToolbarModule,
  MatTabsModule,
  MatListModule,
  MatInputModule,
  MatSelectModule,
  MatCheckboxModule,
  MatMenuModule,
  MatSnackBarModule,
  MatButtonToggleModule,
  MatRadioModule,
  MatAutocompleteModule,
  MatExpansionModule,
  MatSlideToggleModule,
  MatStepperModule,
  MatDatepickerModule,
  MatNativeDateModule,
  MatTooltipModule,
  MatProgressBarModule,
  MatProgressSpinnerModule,
  MatSidenavModule,
  MatTreeModule,
  MatTableModule,
  MatBottomSheetModule,
  MatGridListModule,
  MatSliderModule
} from '@angular/material';


@NgModule({
  imports: [
    MatCardModule,
    MatIconModule,
    MatButtonModule,
    MatToolbarModule,
    MatTabsModule,
    MatListModule,
    MatInputModule,
    MatSelectModule,
    MatCheckboxModule,
    MatMenuModule,
    MatSnackBarModule,
    MatButtonToggleModule,
    MatRadioModule,
    MatDialogModule,
    MatAutocompleteModule,
    MatExpansionModule,
    MatSlideToggleModule,
    MatStepperModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatTooltipModule,
    MatProgressBarModule,
    MatProgressSpinnerModule,
    MatTreeModule,
    MatTableModule,
    MatSidenavModule,
    MatGridListModule,
    MatSliderModule
  ],
  exports: [
    MatCardModule,
    MatIconModule,
    MatButtonModule,
    MatToolbarModule,
    MatTabsModule,
    MatListModule,
    MatInputModule,
    MatSelectModule,
    MatCheckboxModule,
    MatMenuModule,
    MatSnackBarModule,
    MatButtonToggleModule,
    MatRadioModule,
    MatDialogModule,
    MatAutocompleteModule,
    MatExpansionModule,
    MatSlideToggleModule,
    MatStepperModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatTooltipModule,
    MatProgressBarModule,
    MatProgressSpinnerModule,
    MatTreeModule,
    MatTableModule,
    MatSidenavModule,
    MatGridListModule,
    MatBottomSheetModule,
    MatSliderModule
  ]
})
export class AppMaterialModule { }
